language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpenv rehash

install:
  composer install

script:
  - mkdir vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility
  - mv * vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility
  - cd vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility
  - export TRAVIS_CI_TEST = 1
  - phpunit --configuration phpunit.xml